apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes gorush
name: gorush
version: 0.1.0
sources:
  - https://github.com/EENCloud/gorush
maintainers:
  - name: Brandon Reynolds
    email: breynolds@eagleeyenetworks.com
  - name: Peter Whiteside
    email: pwhiteside@eagleeyenetworks.com