resource_types:
- name: helm
  type: docker-image
  source:
    repository: linkyard/concourse-helm-resource
    tag: latest
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
- name: notify
  type: slack-notification
  source:
    url: ((slack-webhook))

- name: stage
  type: helm
  source:
    cluster_url: https://cluster.stage.eencloud.com:6443
    cluster_ca: {{cluster_ca}}
    admin_cert: {{admin_cert}}
    admin_key: {{admin_key}}
    repos:
      - name: charts
        url: https://eencloud.github.io/charts/

- name: aus1p1
  type: helm
  source:
    cluster_url: https://cluster.aus1p1.eencloud.com:6443
    cluster_ca: {{cluster_ca}}
    admin_cert: {{admin_cert}}
    admin_key: {{admin_key}}
    repos:
      - name: charts
        url: https://eencloud.github.io/charts/

#- name: hkg1p1
#  type: helm
#  source:
#    cluster_url: https://cluster.hkg1p1.eencloud.com:6443
#    cluster_ca: {{cluster_ca}}
#    admin_cert: {{admin_cert}}
#    admin_key: {{admin_key}}
#    repos:
#      - name: charts
#        url: https://eencloud.github.io/charts/

- name: gorush
  type: git
  source:
    uri: git@github.com:EENCloud/gorush.git
    branch: master
    private_key: ((github-private_key))

- name: version
  type: semver
  source:
    driver: s3
    initial_version: 0.1.0
    bucket: een-source
    key: gorush
    access_key_id: ((aws_access_key))
    secret_access_key: ((aws_secret_key))

- name: image
  type: docker-image
  source:
    repository: docker.eencloud.com/gorush

jobs:
- name: build
  public: false
  plan:
  - get: gorush
    trigger: true
  - get: version
    params: {bump: patch}
  - put: image
    params:
      build: gorush
      cache: true
      cache_tag: latest
      tag_file: version/version
      tag_as_latest: true
    get_params:
      skip_download: true
  - put: version
    params: {file: version/version}

- name: deploy-to-staging
  public: false
  plan:
  - get: version
    trigger: true
    passed:
    - build
  - put: stage
    params:
      chart: charts/gorush
      release: gorush
      wait_until_ready: 600
      override_values:
      - key: version
        path: version/number
      - key: image.tag
        path: version/number
        type: string
      - key: eenDhashAddress
        value: 192.40.4.24
      - key: secret.iosProdCert
        value: ((iosProdCert))
        hide: true
      - key: secret.androidApiKey
        value: ((androidApiKey))
        hide: true

- name: acceptance-tests
  public: false
  build_logs_to_retain: 100
  plan:
  - get: version
    trigger: true
    passed:
    - deploy-to-staging
  - task: acceptance-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: debian, tag: latest}
      run:
        path: sh
        args:
        - -exc
        - |
          echo "WE NEED TESTS HERE!" && exit 0
    on_failure:
      put: notify
      params:
        username:  concourse
        icon_url:  https://concourse-ci.org/images/trademarks/concourse-black.png
        text: "$BUILD_PIPELINE_NAME - Acceptance test FAILED. :poop-x: <https://concourse.aus1hub1.eencloud.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Click here for logs!>"
    on_success:
      put: notify
      params:
        username:  concourse
        icon_url:  https://concourse-ci.org/images/trademarks/concourse-black.png
        text: "$BUILD_PIPELINE_NAME - Acceptance test SUCCEEDED. :bananadance: <https://concourse.aus1hub1.eencloud.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Click here for logs!>"

- name: deploy-to-prod
  public: false
  plan:
  - get: version
    trigger: false
    passed:
    - acceptance-tests
  - put: aus1p1
    params:
      chart: charts/gorush
      release: gorush
      wait_until_ready: 600
      override_values:
      - key: version
        path: version/number
      - key: image.tag
        path: version/number
        type: string
      - key: eenDhashAddress
        value: 192.40.4.24
      - key: secret.iosProdCert
        value: ((iosProdCert))
        hide: true
      - key: secret.androidApiKey
        value: ((androidApiKey))
        hide: true

#- name: deploy-to-asia
#  public: false
#  plan:
#  - get: version
#    trigger: false
#    passed:
#    - acceptance-tests
#  - put: hkg1p1
#    params:
#      chart: charts/gorush
#      release: gorush
#      wait_until_ready: 600
#      override_values:
#      - key: environment
#        value: prod
#      - key: version
#        path: version/number
#      - key: image.tag
#        path: version/number
#        type: string